"""
tools/email_send.py
-------------------
Mock email-sending tool.

HARD INVARIANT — the only public function is:

    send_email(drafted_email, lead, approval_token) -> dict

There is NO code path that sends an email without a valid approval_token.
There is NO dry_run flag, NO test-bypass parameter, NO default-approved mode.
If approval_token is missing, empty, or not a valid UUID-4 string, this
function raises SendNotAuthorisedError unconditionally.

In production, replace the mock body with a real API call (SendGrid, SES, etc.)
while keeping the same signature and the same token-check guard at the top.
"""

from __future__ import annotations

import re
import uuid
from datetime import datetime, timezone
from typing import Final

from agent.models import DraftedEmail, Lead

# ---------------------------------------------------------------------------
# Sentinel exception — callers must catch this specifically so it's never
# silently swallowed by a bare `except Exception`.
# ---------------------------------------------------------------------------

class SendNotAuthorisedError(Exception):
    """
    Raised when send_email() is called without a valid approval token.

    This exception signals a broken pipeline invariant — it should never be
    caught and suppressed.  Let it propagate so the bug is visible immediately.
    """


# UUID-4 pattern used to validate approval tokens.
_UUID4_RE: Final[re.Pattern] = re.compile(
    r"^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$",
    re.IGNORECASE,
)


def send_email(
    drafted_email: DraftedEmail,
    lead: Lead,
    approval_token: str,
) -> dict:
    """
    Mock-send an outreach email to a lead.

    Parameters
    ----------
    drafted_email : DraftedEmail
        The (possibly rep-edited) draft to send.
    lead : Lead
        The recipient lead record.
    approval_token : str
        Single-use UUID token produced by approval_gate.request_approval().
        Must be a valid UUID-4 string; raises SendNotAuthorisedError otherwise.

    Returns
    -------
    dict
        Confirmation payload with message_id, timestamp, and send status.

    Raises
    ------
    SendNotAuthorisedError
        If approval_token is absent, empty, or not a valid UUID-4 string.
        This is a hard-fail — there is no fallback, no retry, no bypass.
    """
    # ── Token validation — runs before ANY other logic ────────────────────────
    if not approval_token or not isinstance(approval_token, str):
        raise SendNotAuthorisedError(
            "send_email() called without an approval_token. "
            "All emails MUST pass through approval_gate.request_approval() first. "
            "This is a pipeline invariant violation."
        )

    if not _UUID4_RE.match(approval_token.strip()):
        raise SendNotAuthorisedError(
            f"send_email() called with an invalid approval_token={approval_token!r}. "
            "Token must be a UUID-4 string generated by approval_gate.request_approval(). "
            "Do not fabricate or reuse tokens."
        )

    # ── Mock send ─────────────────────────────────────────────────────────────
    message_id = f"mock-msg-{uuid.uuid4()}"
    sent_at = datetime.now(tz=timezone.utc).isoformat()

    print(f"\n  ✉  MOCK SEND — approval_token={approval_token}")
    print(f"     To      : {lead.name} <{lead.email}>")
    print(f"     Subject : {drafted_email.subject}")
    print(f"     Msg ID  : {message_id}")
    print(f"     Sent at : {sent_at}")

    return {
        "status": "sent",
        "message_id": message_id,
        "to_email": str(lead.email),
        "to_name": lead.name,
        "subject": drafted_email.subject,
        "approval_token_used": approval_token,
        "sent_at": sent_at,
        "mock": True,
    }
